version: '3.8'
services:
  fastify_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on: 
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: money_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - fastify_backend

volumes:
  fastify_volume: {}
